#!/usr/bin/env python3
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAIN_C = ROOT / "picocalc/src/main.c"
APPS_C = ROOT / "picocalc/src/apps.c"
COMMANDS_MD = ROOT / "docs/COMMANDS.md"
REPORTS_DIR = ROOT / "reports"
DOCS_DIR = ROOT / "docs"


def extract_shell_cmds(text: str):
    m = re.search(r"static\s+const\s+cmd_meta_t\s+_cmd_registry\s*\[\]\s*=\s*\{(.*?)\};", text, re.S)
    if m:
        body = m.group(1)
        cmds = re.findall(r'\{\s*"([^"]+)"\s*,\s*"[^"]+"\s*\}', body)
        if cmds:
            return cmds

    # X-macro fallback used by main.c registry definitions.
    macro_cmds = re.findall(r'\bX\(\s*"([^"]+)"\s*,\s*"[^"]+"\s*\)', text)
    if macro_cmds:
        return macro_cmds

    m = re.search(r"static\s+const\s+char\s*\*\s*_shell_cmds\s*\[\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        return []
    body = m.group(1)
    return re.findall(r'"([^"]+)"', body)


def extract_app_cmds(text: str):
    m = re.search(r"static\s+bool\s+app_dispatch_named\s*\([^)]*\)\s*\{[^{}]*?\bapp_cmd_entry_t\s+table\[\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        return []
    body = m.group(1)
    return re.findall(r'\{\s*"([^"]+)"\s*,', body)


def extract_doc_commands(text: str):
    """Parse command names from docs/COMMANDS.md table rows.

    For each row, look only at the FIRST table column (between the first
    two `|`). Within that cell, every backticked segment is treated as
    one or more aliases (split on '/'); the leading word of each piece
    is the command name. Tokens that are option flags, ALL-CAPS
    metavars, or bracketed placeholders are skipped so things like
    `uname [-a]` or `sleep MS` don't pollute the diff.
    """
    cmds = set()
    for line in text.splitlines():
        if not line.startswith("| "):
            continue
        # Split into table cells; the first cell is index 1 (index 0 is empty).
        parts = line.split("|")
        if len(parts) < 3:
            continue
        cell = parts[1]
        for seg in re.findall(r"`([^`]+)`", cell):
            for piece in seg.split("/"):
                piece = piece.strip()
                if not piece:
                    continue
                token = piece.split()[0]
                if token.startswith("-") or token.startswith("["):
                    continue
                if token.isupper() and token.isalpha():
                    continue
                token = token.rstrip(",;:")
                if token:
                    cmds.add(token)
    return cmds


def write_markdown(commands, out_path: Path):
    lines = [
        "# Generated Command Registry",
        "",
        "This file is generated by tools/commands/build_registry.py.",
        "",
        "| Command | Source |",
        "| --- | --- |",
    ]
    for cmd in commands:
        lines.append(f"| `{cmd['name']}` | {cmd['source']} |")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_coverage_markdown(runtime_cmds, doc_cmds, out_path: Path):
    runtime_set = {c["name"] for c in runtime_cmds}
    missing = sorted(runtime_set - doc_cmds)
    extra = sorted(doc_cmds - runtime_set)

    lines = [
        "# Command Coverage Report",
        "",
        f"Runtime commands: {len(runtime_set)}",
        f"Documented commands detected: {len(doc_cmds)}",
        f"Missing in docs: {len(missing)}",
        f"Documented but not in runtime: {len(extra)}",
        "",
        "## Missing in docs",
    ]
    if missing:
        for cmd in missing:
            lines.append(f"- `{cmd}`")
    else:
        lines.append("- none")

    lines.append("")
    lines.append("## Documented but not in runtime")
    if extra:
        for cmd in extra:
            lines.append(f"- `{cmd}`")
    else:
        lines.append("- none")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return missing


def main():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    main_text = MAIN_C.read_text(encoding="utf-8")
    apps_text = APPS_C.read_text(encoding="utf-8")
    docs_text = COMMANDS_MD.read_text(encoding="utf-8")

    shell_cmds = sorted(set(extract_shell_cmds(main_text)))
    app_cmds = sorted(set(extract_app_cmds(apps_text)))

    commands = []
    for cmd in shell_cmds:
        commands.append({"name": cmd, "source": "shell completion"})
    app_set = {c["name"] for c in commands}
    for cmd in app_cmds:
        if cmd in app_set:
            continue
        commands.append({"name": cmd, "source": "app dispatch"})

    commands = sorted(commands, key=lambda x: x["name"])

    registry_json = REPORTS_DIR / "command-registry-latest.json"
    registry_md = DOCS_DIR / "COMMANDS.generated.md"
    coverage_md = REPORTS_DIR / "command-coverage-latest.md"

    registry_json.write_text(json.dumps(commands, indent=2) + "\n", encoding="utf-8")
    write_markdown(commands, registry_md)

    doc_cmds = extract_doc_commands(docs_text)
    missing = write_coverage_markdown(commands, doc_cmds, coverage_md)

    print(f"Wrote {registry_json}")
    print(f"Wrote {registry_md}")
    print(f"Wrote {coverage_md}")
    print(f"Missing command docs: {len(missing)}")


if __name__ == "__main__":
    main()
